### ISSUE TITLE
Default port (9125) is different from statsd 8125 default port

### ISSUE THREAD

**Issue by bsergean** [Gr1N/aiodogstatsd#16]
Thanks for a great library, other than that everything seems to work well.

This caused me a tiny bit of trouble to figure out ... is data dog using 9125 ?

**Comment by Gr1N** [comment]
Hi!

9125 is a default port for [`statsd_exporter`](https://github.com/prometheus/statsd_exporter) and yes it's different from `statsd` or `DataDog`. I don't think that I want to change defaults, but I can improve documentation.

@bsergean what do you think?

**Comment by bsergean** [comment]
Got it. What most people do is copy paste 'connect' examples from the readme, so I'd suggest adding a small note there. Thanks !

**Comment by Gr1N** [comment]
You’re welcome. I will keep issue open to not to forget to add notes in README.md.

**Comment by bsergean** [comment]
Sounds good.

**Comment by Gr1N** [comment]
Documentation updated.

**Comment by bsergean** [comment]
Great thanks.
