### ISSUE TITLE
Feature suggestion - timed task

### ISSUE THREAD

**Issue by aviramha** [Gr1N/aiodogstatsd#28]
Hi,
In our use case we've implemented a function for timing asyncio tasks - essentially we have a wrapper function for create_task that adds done callback that sends the metric of duration, if exceeds certain threshold.
I wonder if it's something that would be welcome in this library, if so I'll create a PR!

**Comment by Gr1N** [comment]
@aviramha do you want to implement something more as a part of this task? Or everything is implemented in #27 and we can close issue?
